### ISSUE TITLE
how to deal with илик

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#1]
## Meaning, distribution

The form "илик" only occurs in verb forms and adjusts the meaning to something like "not yet":

> Оҥоро иликпин "Я ещё не сделал"
> Оҥоро иликкин "Ты ещё не сделал"
> Оҥоро иликпит "Мы ещё не сделали"

Aside from its use in finite verb complexes, it can also be attributive (verbal adjective):
> бара илик киһи "A person who hasn't gone yet"

## Similar things in other languages

Kyrgyz is the only language where we've implemented something similar:

```
"<бара элекмин>"
	"бар" v iv notyet p1 sg
```

```
"<бара элек>"
	"бар" v iv gpr_notyet
"<киши>"
	"киши" n nom
```

There's also a gerund reading, in constructions like:
```
"<бара электе>"
	"бар" v iv ger_notyet loc
```
and
```
"<бара элегимде>"
	"бар" v iv ger_notyet px1sg loc
```

**Comment by jonorthwash** [comment]
The initial approach would be to treat it similarly as in Kyrgyz, but we should probably find a better name than "notyet".  There's a grammatical term used for this in some grammars; need to check that.

**Comment by jonorthwash** [comment]
@varie, could you find out what Sakha grammars call forms with илик ?

**Comment by jonorthwash** [comment]
Tuvan has this too; Anderson and Harrison (1999, 45) call it "unaccomplished" and uses `UNACMPL` as the grammatical abbreviation.

**Comment by jonorthwash** [comment]
In [apertium-tyv](https://github.com/apertium/apertium-tyv) we have
```
%<unac%>:%>%{g%}%{A%}л%{A%}к V-PERS-S2 ;
```
and
```
%<gna_unac%>:%>%{g%}%{A%}л%{A%}кт%{A%} # ;
```

**Comment by jonorthwash** [comment]
We seem to have the following currently in apertium-sah:
```
%<gna_nond%>:%>%{A%}% илик CLITICS-NO-COP ; ! FIXME: check
```

What's `nond` stand for?

**Comment by ftyers** [comment]
@jonorthwash I'm not sure, and I also can't remember which grammar(s) we looked at when working on the morphotactics... @varie could you give us 2-3 example sentences with `-{A} илик` ?

**Comment by jonorthwash** [comment]
@ftyers, see examples in the initial issue comment.  Both examples are just like the Kyrgyz one.

**Comment by varie** [comment]
Examples:

> үлэ ноҕурууската саҕалана илик
> кимтэн төрүттээхтэрэ өссө ситэ биллэ илик
>  “150000000” поэма сахалыыта күн бүгүҥҥэ дылы көстө илик

**Comment by jonorthwash** [comment]
This has been taken care of; cf. https://github.com/apertium/apertium-sah/commit/ea8ace4f0d80bde40b165637c4aecc68d8ab6cf9 .
