### ISSUE TITLE
-дээх

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#12]
I'm finding a lot of forms with -дээх, mostly after №, like this:

    27 №-дээх оскуолаҕа

What is this form?

**Comment by varie** [comment]
It's -лаах (-даах, -наах, -таах) affix. It forms adjectives, for example, өйдөөх smart (one who has mind), күүстээх, strong (one who has strength) дьоллоох happy (one who has happiness), etc. (Ubryatova's book, p. 163). №-дээх is word нүөмэрдээх written using № symbol.

**Comment by jonorthwash** [comment]
Ah, this is a denominal adjective suffix.  So it's derivational, which means all the forms should just be entered in lexc, and we shouldn't try to derive them.  Usually.
