### ISSUE TITLE
negative form of -ыы/-һын

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#13]
@varie, what are the negative forms of e.g., барыы, барааһын?

**Comment by jonorthwash** [comment]
Also, you said you think it can decline and gave this example:

> Оҕоҕо үчүгэйи оҥорууну минньигэһи элбэхтик сиэтии, маанытык таҥыннаран баран үчүгэй оонньуурдарынан оонньото сылдьыы уонна бары баҕатын толоруу курдук саныы үөрэммиппит сыыһа.

Which word is the inflected gerund?  Could you put some inflected forms in the ger2.yaml file?

**Comment by varie** [comment]
> what are the negative forms of e.g., барыы, барааһын?

I am not sure about negative forms. Is it possible that there is no negative forms?

> Which word is the inflected gerund?

оҥорууну is accusative of оҥоруу.

> Could you put some inflected forms in the ger2.yaml file?

I added them in https://github.com/apertium/apertium-sah/commit/a9aed16ff3c25b54f79753f1fc8c3009f20b12fa.

**Comment by jonorthwash** [comment]
> I am not sure about negative forms. Is it possible that there is no negative forms?

It's entirely possible.  Let's assume there aren't for now.

> оҥорууну is accusative of оҥоруу.

Looks like that's working: `^оҥорууну/оҥоруу<n><acc>/оҥор<v><tv><ger2><acc>$`

> I added them in a9aed16.

As of bcbffc4, these are passing 100%!

```
[PASS] Test 0: -ыы (Lexical/Generation) 111/0/111
[PASS] Test 1: -ыы (Surface/Analysis) 111/0/111
[PASS] Test 2: -һын (Lexical/Generation) 5/0/5
[PASS] Test 3: -һын (Surface/Analysis) 5/0/5
```
