### ISSUE TITLE
morphotactics for numbers, etc.

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#16]
Beginning of imaginary phonology was implemented in e3abeab.  Now we need some real morphotactics for numbers, including the `%` symbol.

**Comment by ftyers** [comment]
@varie how are case forms after numerals written in Sakha ? Can you give some examples ?

**Comment by varie** [comment]
| case | биир | уон биэс | биэс уон алта |
| ------------- | ------------- |------------- | ------------- |
| `nom` | биир | уон биэс | биэс уон алта |
| `par` | биирдэ | уон биэстэ | биэс уон алтата |
| `acc` | биири | уон биэһи | биэс уон алтаны |
| `dat` | бииргэ | уон биэскэ | биэс уон алтаҕа |
| `abl` | бииртэн | уон биэстэн | биэс уон алтаттан |
| `ins` | бииринэн | уон биэһинэн	| биэс уон алтанан |
| `com` | биирдиин | уон биэстиин | биэс уон алталыын |
| `comp` | биирдээҕэр | уон биэстээҕэр | биэс уон алтатааҕар |

source: [wiki.sakhatyla.ru](http://wiki.sakhatyla.ru/wiki/%D0%93%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0_%D1%8F%D0%BA%D1%83%D1%82%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0/%D0%9C%D0%BE%D1%80%D1%84%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F#.D0.A7.D0.B8.D1.81.D0.BB.D0.B8.D1.82.D0.B5.D0.BB.D1.8C.D0.BD.D1.8B.D0.B5)

**Comment by jonorthwash** [comment]
@varie, how about if the numbers are written as 1, 15, 56, etc.?  How are the case forms written then?  Which (if any) of these are right: "1дэ", "1-дэ", "1'дэ", etc.?

**Comment by varie** [comment]
@jonorthwash I found 158 matches for regexp "[0-9]-дэ" and 2221 matches for "[0-9]-тэ" in newspapers corpus consisting of 16,436,999 tokens, whereas I found only 1 match for "[0-9]тэ" and no matches for [0-9]'дэ. Thus, I think that people usually use "1-дэ" format.

**Comment by jonorthwash** [comment]
Is it the same for possessive morphology, plural, etc?

Are there any major restrictions in terms of which nominal morphology numbers can take?

Also, a more revealing search might be "[0-9]-[дтн][аэоө] ".  I think that should cover all the forms of `<par>`?

**Comment by jonorthwash** [comment]
I updated some stuff for the numbers (01f1f9f5a9393ce74efd7b9ff35ea37c62d0cd85), but need some tests to verify the phonology.  @varie, could you make a `yaml` file matching the following numbers with the following cases?

numbers: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100
cases: `<par>`, `<acc>`, `<dat>`

**Comment by varie** [comment]
@jonorthwash, I added numerals.yaml to tests (7213d2e95873d51a3c86653845cfb116bf39aa0b)

**Comment by jonorthwash** [comment]
I fixed the numerals tests (74e1ff7f661451b7d349182574c6e0dcf6bd83be).  They reveal a few pieces of phonology that are broken, assuming they are right.  But what we really need for this issue is digits.  Could you make an equivalent file for those?

**Comment by jonorthwash** [comment]
Okay, I converted `numerals.yaml` to `digits.yaml`.  Could you check it for accuracy?

**Comment by jonorthwash** [comment]
Everything is working in that tests file as of f40bac3 except the following:
```
[1/3][FAIL] 6<num><subst><acc> => Missing results: 6-ты
[1/3][FAIL] 6<num><subst><acc> => Unexpected results: 6-ны
[2/3][PASS] 6<num><subst><par> => 6-та
[3/3][FAIL] 6<num><subst><dat> => Missing results: 6-ны
[3/3][FAIL] 6<num><subst><dat> => Unexpected results: 6-ҕа
```

This looks to me like there are errors in the expected forms.  @varie, could you check `numerals.yaml` and `digits.yaml`?

**Comment by varie** [comment]
@jonorthwash yes, there were errors :(. I fixed them in a639cdf9a882ea66d47bb00838119d582cfbef3f :).

**Comment by jonorthwash** [comment]
Looking good.

We're getting forms in the various corpora like "20-с" and "179-с".  How should we analyse these?

**Comment by jonorthwash** [comment]
Also, does т alternate with д in any words besides түөрт?

**Comment by varie** [comment]
@jonorthwash "20-c" is сүүрбэһис (20th), "179-c" is сүүс сэттэ уон тохсус (179th).

> does т alternate with д in any words besides түөрт?

Hmmm, you mean any any word? For example, орт - ордор?

**Comment by jonorthwash** [comment]
> "20-c" is сүүрбэһис (20th), "179-c" is сүүс сэттэ уон тохсус (179th).

Aha, makes perfect sense, should be easy to handle.

> > does т alternate with д in any words besides түөрт?
>
> Hmmm, you mean any any word? For example, орт - ордор?

Yes, that's a good example. Can you find more?

**Comment by varie** [comment]
@jonorthwash,
Verbs containing %{D%}              ! д/т alternation at the end of some verbs (cf. тарт):
куурт:куур%{D%}
өлөрт:өлөр%{D%}
олорт:олор%{D%}
орт:ор%{D%}
тириэрт:тириэр%{D%}
күүһүрт:күүһүр%{D%}
тарт:тар%{D%}
тиэрт:тиэр%{D%}
сүүрт:сүүр%{D%}
чэбдигирт:чэбдигир%{D%}
саҥарт:саҥар%{D%}
иһэрт:иһэр%{D%}
бытаарт:бытаар%{D%}
эрт:эр%{D%}
итирт:итир%{D%}
уустугурт:уустугур%{D%}
күүрт:күүр%{D%}

**Comment by jonorthwash** [comment]
Aha, good, we already deal with this!

I see that all these examples have the alternation specifically with the т in рт clusters at the end of words.  So I feel compelled to ask: are there any examples of word-final рт that _don't_ have this alternation?

**Comment by jonorthwash** [comment]
Hmm so the behaviour of these words is confusing me a bit.  Before {T}{A} they do different things, depending on the meaning of {T}{A}?

`тарт<v><tv><ifi><p3><sg> : тар{D}>{T}{A} : тарта`
but
`түөрт<num><subst><par> : түөр{D}>{T}{A} : түөрттэ`
?

That is, the extra т deletes in past tense, but doesn't in partitive case?

**Comment by varie** [comment]
@jonorthwash I think I made a mistake with "түөрттэ", I think it should be "түөртэ", since I found 154 matches for  "түөртэ" in the newspaper corpus and no any match for "түөрттэ".

**Comment by jonorthwash** [comment]
So it's "түөртэ" and "4-э" (and not "4-тэ"?)?

**Comment by jonorthwash** [comment]
Okay, I think I've taken care of this now, in 73daa8b13d72df483bc6615569bf6e3b0c06c18c.  We can probably close this issue now.
