### ISSUE TITLE
negative of <ger_pot>

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#26]
көрүө, кэлиэ, барыа (бар-, бараа-)

**Comment by varie** [comment]
At first I thought that they might be:
көрүө—көрүмүө,
кэлиэ—кэлимиэ, 
барыа(бар-)—барымыа.
бараа(бараа-)—бараамыа.
I guess I constructed them by analogy with көрүөx-көрүмүөx forms.
But then I didn't find those forms in corpora, so I thought that maybe those made only analytically:
көрүө—көрүө суоҕа,
кэлиэ—кэлиэ суоҕа, 
барыа(бар-)—барыа суоҕа,
барыа(бараа-)—барыа суоҕа.

**Comment by jonorthwash** [comment]
So we're going with the analytic forms?  Do the forms of суоҕа change for person, number, etc.?  Can they take case endings?

**Comment by varie** [comment]
Hmm, I guess they change by number and person:
көрүө суохпут,
көрүө суоххут,
көрүө суохтара—or are those not gerund anymore?

I guess they can take case endings:
көрүө суоҕунан, көрүө суоҕунааҕар;
көрүө суохтарынан.

**Comment by jonorthwash** [comment]
> I guess they can take case endings:
> көрүө суоҕунан, көрүө суоҕунааҕар;
> көрүө суохтарынан.

Does this mean like, "by the fact that they couldn't see" and the like?  Or something else?

**Comment by varie** [comment]
Yes

**Comment by jonorthwash** [comment]
What about "by the fact that they could see"?  We've limited the affirmative forms to only have nominative forms and no possessive forms—is that right?

**Comment by jonorthwash** [comment]
Okay, interesting.  In that case, we can close this issue.
