### ISSUE TITLE
-AAт forms

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#29]
There are verb forms in `-{A}{A}т` that are identified by [Johanson (2021)](https://doi.org/10.1017/9781139016704.046) as a type of converb.  Examples: биэрээт, түһээт, ылаат.

(An English gloss of these forms appears to be "as soon as X Y-ed" or "upon having Y-ed"?  In Kyrgyz these semantics are expressed with a VN+possessive ending followed by a postposition, e.g. берээрим менен - "as soon as I gave".  So no help to the following questions.)

I guess we need a verbal adverb label (`gna_???`) for these.  Aside from the question of what the label should be, I'm wondering if these might behave as infinitives too (that is, occur with auxiliaries, `prc_???`).  @varie?

**Comment by jonorthwash** [comment]
@varie, are there negative forms of these?

**Comment by varie** [comment]
Yes, for example: "барымаат", "кэлимээт", "көрүмээт", "сылдьымаат".
