### ISSUE TITLE
verbs like сырыт/сылдьар

### ISSUE THREAD

**Issue by varie** [apertium/apertium-sah#3]
- [ ] ыарый/ыалдьар
- [ ] оҕус/охсор
- [ ] араҕыс/арахсар
- [ ] сайын/сайдар
- [ ] умун/умнар
- [ ] үтүгүн/үтүктэр

- [ ] эбилин/эбиллэр
- [ ] бэрилин/бэриллэр
- [ ] иҥэрилин/иҥэриллэр
- [ ] иһилин/иһиллэр
- [ ] талылын/талыллар
- [ ] туһанылын/туһаныллар

- [ ] төнүн/төннөр
- [ ] кытын/кыттар

- [x] орт/ордор
- [x] тарт/тардар
- [ ] тириэрт/тириэрдэр

- [x] сыһын/сыстар

**Comment by varie** [comment]
сыһын/сыстар

**Comment by ftyers** [comment]
@varie can you tell us a bit what is going on here?  What are those forms ?

**Comment by varie** [comment]
These are imp, p2, sg and aor, p3, sg forms. aor forms weren't analysed, because of some phonological changes occur there. Now part of them is working.

**Comment by jonorthwash** [comment]
Most of these are working now—just not the ones with т/д alternation.  @varie, could you check the forms in the `"Verbs with voicing of final coronals"` section of `aorist.yaml`?

**Comment by varie** [comment]
> could you check the forms in the "Verbs with voicing of final coronals" section of aorist.yaml?

I checked that section and changed a bit in https://github.com/apertium/apertium-sah/commit/223c26107bfffd9025c1707b9651205d9b922b2c.

**Comment by jonorthwash** [comment]
I have those forms working now too, in 5353300.

**Comment by jonorthwash** [comment]
I have basically all of aorist.yaml passing, so I'm going to close this issue.
