### ISSUE TITLE
буолуон

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#4]
What's буолуон mean?  Is this a form of буол?  If so, how is the suffix `{I}{A}н` used?

**Comment by varie** [comment]
Yes, it is form of буол.
Closest form I found in Ubryatova book[1] is:

> Причастие на -ыах, присоединяя аффиксы принадлежности, образует будущее время изъявительного наклонения:
> барыаҕым "пойду, поеду"
> барыаҕыҥ "пойдешь, поедешь"
> барыаҕа "пойдет, поедет"
> барыахпыт "пойдем, поедем"
> барыаххыт "пойдете, поедете"
> барыахтара "пойдут, поедут"
> 
> барыам суоҕа "не пойду, не поеду"
> барыаҥ суоҕа "не пойдешь, не поедешь"
> барыа суоҕа "не пойдет, не поедет"
> барыахпыт суоҕа "не пойдем, не поедем"
> барыаххыт суоҕа "не пойдете, не поедете"
> барыахтара суоҕа "не пойдут, не поедут"
> 
> Единственное число положительной формы будущего времени в якутском языке имеет параллельно употребляемый фонетически-стяженный вариант: мин барыам, эн _барыаҥ_, кини барыа.

It might be a contracted form of future tense singular 2 person but with substitution of ҥ by н for some reason.

Also in Wikipedia corpus it is often found as "буолуон сөп" -  "может быть" - "might be". 
443 out of 606 occurrences of "буолуон" are found as "буолуон сөп".
Examples:
Ыйааһына 9 киилэттэн 30 киилэҕэ диэри буолуон сөп. - Its weight might be between 9 to 30 kilograms.
Онон бу кэлин үөскээбит өйдөбүл буолуон сөп курдук. - That's why it might be a notion which has been created lately.

So it might be some another form, but I couldn't find it in the book.
 
1. Убрятова Е.И. (ред.). Грамматика современного якутского литературного языка. Том 1. Фонетика и морфология (Часть 1 - Фонетика). М.: Наука, 1982. – 496 с.

**Comment by jonorthwash** [comment]
Yeah, I couldn't find it in that book either—that's why I opened this issue.  Even the best grammars often miss things.

You comments on this issue so far are really helpful.  With a little more info we might be able to categorise the form ourselves.

1. What does "сөп" mean in other contexts?
2. How are some of the other occurrences of "буолуон" in the corpus used?  That is, could you gloss some more examples, but ones without "сөп"?
3. Can other verbs occur in the same forms in the same contexts?  For example, could you say "барыан сөп", "киириэн сөп", etc.?  (Examples?)  What about other contexts, like those you found for question 2 above?

**Comment by varie** [comment]
Nice! :)

1. According to sakhatyla.ru dictionary сөп means:
- _adjective_ right, correct.
сөп санаа - right thought
- yes, okay.
сөп, оҥоруом - okay, I will do it
- _adverb_ enough
сөп улахан - enough big

2. **буолуон син** - it means basically same as буолуон сөп
**буолуон иннинэ** - before it become so
Examples:
президент _буолуон иннинэ_ - _Before becoming_ a president
Ол _буолуон иннинэ_ сорох экономика услуобуйаларын көннөрүөхтээхтэр - _Before it happens_ they need to fix some economical conditions
**буолуон наада**
онон аты бааһырдыбатын диэн ботото халыҥ _буолуон наада_ - therefore to not hurt a horse boto _needs to be_ thick
**буолуон баҕарар**
Хас биирдии төрөппүт оҕото «Үчүгэй оҕо» _буолуон баҕарар_. - Every parent _wants_ that their child is a "good child".
**буолуон баҕарбыта**
Университетка үөрэҕин бүтэрэн баран философия учуутала _буолуон баҕарбыта_ да олус ыарахан буолбута. - After graduating from university (she/he) _wanted to become_ a philosophy teacher but it was too difficult.
There might be other occurrences also.

3. Yes, it is possible to say "барыан сөп", "киириэн сөп"
таҥара үөрэҕин тарҕатыы быдан түргэнник _барыан сөп_ - spreading of religious studies  _might go_ much faster
олох сайдыы суолугар _киириэн сөп_ - life _might enter_ to road of development
It is possible to say "барыан син", "барыан наада", "барыан баҕарар", "барыан баҕарбыта" and "киириэн син", "киириэн наада", "киириэн баҕарар", "киириэн баҕарбыта".
Хайдах эмэ эрдэлээн туран детсадка _барыан баҕарар_ оҕоҕо бэйэтэ таҥнарыгар бириэмэ биэрии, кэтэһии оҕо үөрэнэрин лаппа түргэтэтиэн сөп. - Somehow waking up earlier and giving time and waiting a child who wants to go to kindergarten to put on her/his clothes _might_ speed up child's process of learning.

**Comment by jonorthwash** [comment]
Okay, it looks a lot like a verbal noun suffix.  Can forms with this suffix take case or possessive suffixes too?

**Comment by varie** [comment]
No, I think they cannot.
It's not right to say, for example, буолуоны, буолуона, etc.

**Comment by jonorthwash** [comment]
Also, @varie, is there a negative version of these forms?

**Comment by varie** [comment]
Yes: буолумон, кииримиэн, барымыан.

**Comment by jonorthwash** [comment]
Ah cool.  And what do the negative forms look like after forms with various vowels?

**Comment by varie** [comment]
> And what do the negative forms look like after verbs ending with various vowels?

Could you provide some examples, please?

Also, I found in Ubryatova book such sentence: "Айаҥҥа _туруон_ биир хонук _иннинэ_ комсомол тэрилтэтин мунньаҕа буолбута" - There was meeting of komsomol organisation day before he left. And she says that it is genitive case of -ыах participle (туруох) with иннинэ postposition.

**Comment by jonorthwash** [comment]
> > And what do the negative forms look like after verbs ending with various vowels?
> Could you provide some examples, please?

So, what do the affirmative and negative of this suffix look like after verbs like диэ, аһаа, төрөө, and ыа?

**Comment by varie** [comment]
> So, what do the affirmative and negative of this suffix look like after verbs like диэ, аһаа, төрөө, and ыа?

I think they would be:
диэн - диэмиэн, аһыан - аһыамыан, төрүөн - төрүөмүөн, ыан - ыамымыан

**Comment by jonorthwash** [comment]
Could you put those in a yaml file?

**Comment by varie** [comment]
> Could you put those in a yaml file?

https://github.com/apertium/apertium-sah/commit/14572f2c240c2f0751cf28f8c8f13fa2f1660c86

**Comment by jonorthwash** [comment]
All of these forms seem to analyse okay; closing for now.
