### ISSUE TITLE
analysis of forms in {I}лл{I}б{I}т

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#6]
There are a lot of what appear to be {I}лл{I}б{I}т forms in the corpus:
```
    799  ^Ылыллыбыт/*Ылыллыбыт$
    158 ^оҥоһуллубут/*оҥоһуллубут$
    134 ^ыҥырыллыбыт/*ыҥырыллыбыт$
    133 ^суруллубут/*суруллубут$
    112 ^тэриллибит/*тэриллибит$
     91  ^ыытыллыбыт/*ыытыллыбыт$
     75  ^Туһаныллыбыт/*Туһаныллыбыт$
     75 ^иҥэриллибит/*иҥэриллибит$
     67 ^көмүллүбүт/*көмүллүбүт$
     48 ^туттарыллыбыт/*туттарыллыбыт$
     47 ^иитиллибит/*иитиллибит$
     44 ^тутуллубут/*тутуллубут$
     40 ^ылыллыбыт/*ылыллыбыт$
     38 ^бэриллибит/*бэриллибит$
     24 ^туруоруллубут/*туруоруллубут$
     24 ^бигэргэтиллибит/*бигэргэтиллибит$
     22 ^айыллыбыт/*айыллыбыт$
     20 ^ылыныллыбыт/*ылыныллыбыт$
```

There are also a bunch that have an extra {A} at the end:
```
    179  ^тэриллибитэ/*тэриллибитэ$
     73 ^иҥэриллибитэ/*иҥэриллибитэ$
     58  ^биллибитэ/*биллибитэ$
     55  ^ыытыллыбыта/*ыытыллыбыта$
     49 ^тутуллубута/*тутуллубута$
     37 ^оҥоһуллубута/*оҥоһуллубута$
     35  ^аһыллыбыта/*аһыллыбыта$
     29 ^арыллыбыта/*арыллыбыта$
     24 ^киллэриллибитэ/*киллэриллибитэ$
     21 ^уһуллубута/*уһуллубута$
     21 ^суруллубута/*суруллубута$
     21 ^бэриллибитэ/*бэриллибитэ$
```

What do these forms mean?  They look almost like passive followed by the past {B}{I}т, but they seem to have an extra vowel.  Is this all they are?  And the ones with {A} are possessives of the past gerund of the passive?

**Comment by varie** [comment]
- {I}лл{I}б{I}т forms seem to be passive followed by the past {B}{I}т. They mean something/someone to what/whom something was done:
ылыллыбыт - something what was picked
оҥоһуллубут - something what was created
ыҥырыллыбыт - someone who was invited

- And the ones with {A} are possessives of the past gerund of the passive?
It also might be singular 3 person преждепрошедшее повествовательное время of passive:
1929 сыллаахха бастакы «Кыайыы» холкуос тэриллибитэ. - First «Кыайыы» kolkhoz was organised around 1929.

**Comment by jonorthwash** [comment]
> It also might be singular 3 person преждепрошедшее

In your example it seems to be that.  Are there also examples of the possessive reading, or no? 


Are there other forms that passive + BIт take, or do all transitive verbs take IллI as passive before BIт?

**Comment by varie** [comment]
> Are there also examples of the possessive reading, or no?

Ah, yes, I found this: "1996 сыл – оскуола тэриллибитэ 110 сыллаах үбүлүɵйэ" - 1996 year is 110 year anniversary of school foundation. Is it the possessive reading?

**Comment by jonorthwash** [comment]
Yes, looks like it.  Can you think of an example with something other than 3rd person?

**Comment by varie** [comment]
Something like "Мин барбытым 3 сыл буолла" - it's been 3 years since I left. (?)
"Эн барбытын 3 сыл буолла"
"Кини барбыта 3 сыл буолла"
"Биһиги барбыппыт 3 сыл буолла"
"Эһиги барбыккыт 3 сыл буолла"
"Кинилэр барбыттара 3 сыл буолла"

**Comment by jonorthwash** [comment]
Yes, awesome!  And can you get the full range of possessive and case endings?  Do they have unexpected forms?

**Comment by varie** [comment]
> And can you get the full range of possessive and case endings?

Yes, it seems to be so:

барбытым
барбыппын
барбыппар
барбыппыттан
барбыппынан
барбыппыныын
барбыппынааҕар

барбытын
барбыккын
барбыккар
барбыккыттан
барбыккынан
барбыккыныын
барбыккынааҕар

барбыта
барбытын
барбытыгар
барбытыттан
барбытынан
барбытыныын
барбытынааҕар

барбыппыт
барбыппытын
барбыппытыгар
барбыппытыттан
барбыппытынан
барбыппытыныын
барбыппытынааҕар

барбыккыт
барбыккытын
барбыккытыгар
барбыккытыттан
бакрбыккытынан
барбыккытыныын
барбыккытынааҕар

барбыттара
барбыттарын
барбыттарыгар
барбыттарыттан
барбыттарынан
барбыттарыныын
барбыттарынааҕар

**Comment by varie** [comment]
And also:

барбыта
барбытын
барбытыгар
барбытыттан
барбытынан
барбыттыын
барбыттааҕар

барбыттара
барбыттарын
барбыттарыгар
барбыттарыттан
барбыттарынан
барбыттардыын
барбыттардааҕар

oh, but барбыт is not passive. But I think same is applicable to, for example, тэриллибит:
тэриллибитим
тэриллибиппин
тэриллибиппэр
тэриллибиппиттэн
тэриллибипинэн
тэрилибиппиниин
тэрилибиппинээҕэр
etc.

**Comment by jonorthwash** [comment]
I believe this is resolved.
