### ISSUE TITLE
analysis of forms in {B}{I}т{I}н

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#7]
There are a number of what appear to be verb forms in {B}{I}т{I}н in the corpus.  What do these mean / how are these used?
```
     58 ^буолбутун/*буолбутун$
     32 ^оҥорбутун/*оҥорбутун$
     21 ^кэлбитин/*кэлбитин$
     16 ^киирбитин/*киирбитин$
     15 ^тахсыбытын/*тахсыбытын$
     15  ^суруллубутунан/*суруллубутунан$
     15 ^барбытын/*барбытын$
     14 ^үөскээбитин/*үөскээбитин$
     14  ^сылдьыбытын/*сылдьыбытын$
     11  ^ылбытын/*ылбытын$
     11 ^хаалбытын/*хаалбытын$
     11 ^суруйбутун/*суруйбутун$
      9 ^суруйбутунан/*суруйбутунан$
      9 ^олорбутун/*олорбутун$
      9 ^биэрбитин/*биэрбитин$
      8 ^эстибитин/*эстибитин$
      8  ^элбээбитин/*элбээбитин$
      8 ^тутуллубутун/*тутуллубутун$
      8 ^төрөөбүтүн/*төрөөбүтүн$
      8 ^талбытынан/*талбытынан$
```

Note the ones with an extra {A}н.

**Comment by varie** [comment]
According to Ubryatova[1], it might be accusative case of -быт participle. For example, "Уйбаан _сылдьыбытын_ кини кэпсээбэтэх" - She/he didn't tell about Ivan was there. And ones with an extra {A}н seems to be instrumental case of the same participle. For example, "Биир сарсыарда почтальон кинини _көрбүтүнэн_ киирдэ" - One morning a postman went inside watching her/him.

1. Убрятова Е.И. (ред.). Грамматика современного якутского литературного языка. Том 1. Фонетика и морфология (Часть 1 - Фонетика). М.: Наука, 1982. – 496 с.

**Comment by jonorthwash** [comment]
Can BIт take other cases?  What about possessive suffixes?  Could you provide some example forms of these as well?

**Comment by varie** [comment]
Yes, it can take other cases and possessive suffixes as well:
"Үҥсүү _киирбитигэр_ милиция кэлбит" - When a complaint was received, police came.
"Хоту участок дьоно _кэлбэтэхтэриттэн_ уопсай мунньах буолбатах" - Due to the fact that people from the northern section did not appear, the general meeting did not take place.

**Comment by jonorthwash** [comment]
This has been dealt with; we now get e.g.

    ^кэлбитин/кэл<v><iv><ger_past><px3sg><acc>$
    ^олорбутун/олор<v><iv><ger_past><px3sg><acc>$
