### ISSUE TITLE
number in 3rd person possessive forms of gerunds

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-sah#9]
We originally had just a `<px3sp>` in the lexicon, but it looks like there are distinct singular and plural forms, e.g.
`барбытыгар/бар<v><iv><ger_past><px3sg><dat>`
`барбыттарыгар/бар<v><iv><ger_past><px3pl><dat>`

However, some recent tests have forms like
`барыахтарыгар/бар<v><iv><ger_fut><px3sp><dat>`

Is `барыаҕыгар` a singular form to this plural form?  Are there any possessives that don't have a distinction?  Alternatively, are singular and plural readings ever ambiguous?

**Comment by jonorthwash** [comment]
@ftyers, so you suggest all "singular" forms should be p3.sp, and all "plural" forms should be p3.pl.  Is that right?

**Comment by ftyers** [comment]
@jonorthwash I think that's a good way forward, yes. Providing it works like in Turkish, where 3SG forms are ambiguous between singular and plural.

**Comment by jonorthwash** [comment]
From IRC:

A strict sg/pl divide in noun possession:
    кини куората = his/her city
    кини куораттара = his/her cities
    кинилэр куораттара = their city / their cities
    *кинилэр куората (impossible)

Finite verb forms seem to be the same way:
    кини барбыта
    кинилер барбыттара

Still looking into gerund forms

**Comment by jonorthwash** [comment]
I've started fixing `sg`/`pl` stuff (cf. bcbffc4), but there's one form that looks like it has double plural that's no longer being analysed: табаардардарын.

@varie, do you know what the right analysis for this form is?  Could it be a double plural?

**Comment by varie** [comment]
> табаардардарын

I think it might be some erroneous form (should be табаардарын (?)).

Ubryatova states that singular and plural 3rd person possessive forms of plural bases coincide: аттара 'his horses' and аттара 'their horses'. She says that this is explained by the fact that the structure of the plural form of the 3rd person possession affix contains an affix -лар (p. 128).

Though табаардардарын query to google search gives 4 results.

**Comment by jonorthwash** [comment]
Resumed in #21.
